name: Build & Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: cd packages/radix-vue && npm install

    - name: Build
      run: cd packages/radix-vue && npm run -r --filter=!docs build

    - name: Check for errors
      run: |
        if [ $? -eq 0 ]; then
          echo "Build succeeded"
        else
          echo "Build failed"
          exit 1
        fi

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: cd packages/radix-vue && npm install

    - name: Lint
      run: cd packages/radix-vue && npm run lint

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: cd packages/radix-vue && npm install

    - name: Test
      run: cd packages/radix-vue && npm run test
